application: tnt-wedding
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))  

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  
#- url: /(.*\.html)
  #mime_type: text/html
  #static_files: static/\1
  #upload: static/(.*\.html)
  #expiration: "1h"

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"

- url: /.*
  script: main.app
